### ISSUE TITLE
Update the executives list

### ISSUE THREAD

**Issue by Peter-Wilson** [BrockCSC/brockcsc.github.io#17]
Update the executives on the Brock CSC website.

**Comment by Peter-Wilson** [comment]
added fahad and moved adam to president. Still need to add everyone else

**Comment by Peter-Wilson** [comment]
List of people to add:
- OB
- Abdul
- Dana
- Patrick
- Lindsey
- Sammi
- Adam Mckinlay

People to remove:
- Peter
- Matt
- James
- Preston (?)

**Comment by JamesEarle** [comment]
Frankly I'm offended
