### ISSUE TITLE
Add github link on website

### ISSUE THREAD

**Issue by kindeep** [BrockCSC/brockcsc.github.io#28]
Add text in footer: Contribute on GitHub, potentially with a logo depending on how it looks and link back to https://github.com/BrockCSC/brockcsc.github.io

**Comment by dsouvage** [comment]
Where should the github link go? The footer?

**Comment by kindeep** [comment]
Potentially, design is open ended, it could potentially go along with the other links, Discord, instagram etc. Supposed to be a link to this repo though.

**Comment by gideonoludeyi** [comment]
done
