### ISSUE TITLE
Build a Static Site Generator

### ISSUE THREAD

**Issue by Chippers255** [BrockCSC/brockcsc.github.io#3]
Due to the site being hosted on github we cannot rely on server side scripting. Therefore we are using a Static website. We need to develop a python site generator so future use/updates to the site can be made easily with minimal chance of creating errors.

**Comment by Chippers255** [comment]
Going to drop this issue, it will take to much time to implement for the minor changes we rarely need to make. Maybe we could make a project of it with the CSC but not for now.

**Comment by dideler** [comment]
:+1: -- agreed that this isn't needed, editing the site as is works well enough.
