### ISSUE TITLE
Update Guide Page to Contain Brock CS information

### ISSUE THREAD

**Issue by dsouvage** [BrockCSC/brockcsc.github.io#31]
Currently the Guide page has nothing related to "guiding" Brock CS students.

It would be good if we got a base level of content or a high level structure so that people can start contributing.

**Comment by kindeep** [comment]
Link to markdown for guide: https://github.com/BrockCSC/brockcsc.github.io/edit/development/src/assets/cs-guide.md

**Comment by gideonoludeyi** [comment]
done
