### ISSUE TITLE
Look into ways of changing nav svg image without changing href

### ISSUE THREAD

**Issue by ilaskaev** [BrockCSC/brockcsc.github.io#8]
Right now, any time the nav changes colour, the mascot image also changes colour. Issue here is that every change causes it to be re-downloaded.

A few solutions I can think of is that the svg can be turned into a webfont, then we can use the `color` property on it. We could also have 2 images loaded and change `display` css properties on them. It'd also work if we created an svg component which inlined the svg and didn't use the `img` tag.

**Comment by fzxt** [comment]
Went with the 2 images approach for now.
